<template><div><h3 id="快速创建内存安全线程池" tabindex="-1"><a class="header-anchor" href="#快速创建内存安全线程池" aria-hidden="true">#</a> 快速创建内存安全线程池</h3>
<p>core 模块 ThreadPoolCreator 类提供快速创建内存安全线程池的静态方法，可以用来替换 Executors 类，
内部是基于 ThreadPoolBuilder 来创建的，也可以通过 ThreadPoolBuilder 来创建线程池对象</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code>
<span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">ThreadPoolExecutor</span> <span class="token function">createCommonFast</span><span class="token punctuation">(</span><span class="token class-name">String</span> threadPrefix<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token class-name">ThreadPoolBuilder</span><span class="token punctuation">.</span><span class="token function">newBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">threadFactory</span><span class="token punctuation">(</span>threadPrefix<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">buildCommon</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">ExecutorService</span> <span class="token function">createCommonWithTtl</span><span class="token punctuation">(</span><span class="token class-name">String</span> threadPrefix<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token class-name">ThreadPoolBuilder</span><span class="token punctuation">.</span><span class="token function">newBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">dynamic</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">threadFactory</span><span class="token punctuation">(</span>threadPrefix<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">buildWithTtl</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">DtpExecutor</span> <span class="token function">createDynamicFast</span><span class="token punctuation">(</span><span class="token class-name">String</span> poolName<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token function">createDynamicFast</span><span class="token punctuation">(</span>poolName<span class="token punctuation">,</span> poolName<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">DtpExecutor</span> <span class="token function">createDynamicFast</span><span class="token punctuation">(</span><span class="token class-name">String</span> poolName<span class="token punctuation">,</span> <span class="token class-name">String</span> threadPrefix<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token class-name">ThreadPoolBuilder</span><span class="token punctuation">.</span><span class="token function">newBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">threadPoolName</span><span class="token punctuation">(</span>poolName<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">threadFactory</span><span class="token punctuation">(</span>threadPrefix<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">buildDynamic</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">ExecutorService</span> <span class="token function">createDynamicWithTtl</span><span class="token punctuation">(</span><span class="token class-name">String</span> poolName<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token function">createDynamicWithTtl</span><span class="token punctuation">(</span>poolName<span class="token punctuation">,</span> poolName<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">ExecutorService</span> <span class="token function">createDynamicWithTtl</span><span class="token punctuation">(</span><span class="token class-name">String</span> poolName<span class="token punctuation">,</span> <span class="token class-name">String</span> threadPrefix<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token class-name">ThreadPoolBuilder</span><span class="token punctuation">.</span><span class="token function">newBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">threadPoolName</span><span class="token punctuation">(</span>poolName<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">threadFactory</span><span class="token punctuation">(</span>threadPrefix<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">buildWithTtl</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">ThreadPoolExecutor</span> <span class="token function">newSingleThreadPool</span><span class="token punctuation">(</span><span class="token class-name">String</span> threadPrefix<span class="token punctuation">,</span> <span class="token keyword">int</span> queueCapacity<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token function">newFixedThreadPool</span><span class="token punctuation">(</span>threadPrefix<span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> queueCapacity<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">ThreadPoolExecutor</span> <span class="token function">newFixedThreadPool</span><span class="token punctuation">(</span><span class="token class-name">String</span> threadPrefix<span class="token punctuation">,</span> <span class="token keyword">int</span> poolSize<span class="token punctuation">,</span> <span class="token keyword">int</span> queueCapacity<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token class-name">ThreadPoolBuilder</span><span class="token punctuation">.</span><span class="token function">newBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">corePoolSize</span><span class="token punctuation">(</span>poolSize<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">maximumPoolSize</span><span class="token punctuation">(</span>poolSize<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">workQueue</span><span class="token punctuation">(</span><span class="token class-name">QueueTypeEnum</span><span class="token punctuation">.</span>MEMORY_SAFE_LINKED_BLOCKING_QUEUE<span class="token punctuation">.</span><span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> queueCapacity<span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">threadFactory</span><span class="token punctuation">(</span>threadPrefix<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">buildDynamic</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">ExecutorService</span> <span class="token function">newCachedThreadPool</span><span class="token punctuation">(</span><span class="token class-name">String</span> threadPrefix<span class="token punctuation">,</span> <span class="token keyword">int</span> maximumPoolSize<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token class-name">ThreadPoolBuilder</span><span class="token punctuation">.</span><span class="token function">newBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">corePoolSize</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">maximumPoolSize</span><span class="token punctuation">(</span>maximumPoolSize<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">workQueue</span><span class="token punctuation">(</span><span class="token class-name">QueueTypeEnum</span><span class="token punctuation">.</span>SYNCHRONOUS_QUEUE<span class="token punctuation">.</span><span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">threadFactory</span><span class="token punctuation">(</span>threadPrefix<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">buildDynamic</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">ThreadPoolExecutor</span> <span class="token function">newThreadPool</span><span class="token punctuation">(</span><span class="token class-name">String</span> threadPrefix<span class="token punctuation">,</span> <span class="token keyword">int</span> corePoolSize<span class="token punctuation">,</span>
                                                   <span class="token keyword">int</span> maximumPoolSize<span class="token punctuation">,</span> <span class="token keyword">int</span> queueCapacity<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token class-name">ThreadPoolBuilder</span><span class="token punctuation">.</span><span class="token function">newBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">corePoolSize</span><span class="token punctuation">(</span>corePoolSize<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">maximumPoolSize</span><span class="token punctuation">(</span>maximumPoolSize<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">workQueue</span><span class="token punctuation">(</span><span class="token class-name">QueueTypeEnum</span><span class="token punctuation">.</span>MEMORY_SAFE_LINKED_BLOCKING_QUEUE<span class="token punctuation">.</span><span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> queueCapacity<span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">threadFactory</span><span class="token punctuation">(</span>threadPrefix<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">buildDynamic</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="责任链模式简单封装" tabindex="-1"><a class="header-anchor" href="#责任链模式简单封装" aria-hidden="true">#</a> 责任链模式简单封装</h3>
<p>common 模块 pattern.filter 包下提供简单责任链模式的封装，在通知告警模块有应用，可以参考</p>
<h3 id="内存安全阻塞队列" tabindex="-1"><a class="header-anchor" href="#内存安全阻塞队列" aria-hidden="true">#</a> 内存安全阻塞队列</h3>
<p>common 模块 queue 包提供内存安全阻塞队列 MemorySafeLinkedBlockingQueue，开发中有需求可以选择使用</p>
<h3 id="配置文件解析器" tabindex="-1"><a class="header-anchor" href="#配置文件解析器" aria-hidden="true">#</a> 配置文件解析器</h3>
<p>core 模块提供 json、properties、yaml 类型配置文件解析器，有需要可以使用</p>
</div></template>
